language: android
sudo: false
jdk: openjdk7
android:
  components:
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository
    - android-23
    - sys-img-armeabi-v7a-android-23
  licenses:
    - '.+'


before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew clean assemble check
  - ./gradlew connectedAndroidTest